// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABe1sO3_Dy_9fQ6Iqan-hUFKyxto7J2IQ',
    appId: '1:75312656911:web:ce82b2819c5ad20d01a97a',
    messagingSenderId: '75312656911',
    projectId: 'buooy-5d81f',
    authDomain: 'buooy-5d81f.firebaseapp.com',
    storageBucket: 'buooy-5d81f.firebasestorage.app',
    measurementId: 'G-0QSRN9FEQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVSIFepGnDE6Ar2yvXnIy0_DCGhvfZ4o',
    appId: '1:75312656911:android:1f727d0d0217963e01a97a',
    messagingSenderId: '75312656911',
    projectId: 'buooy-5d81f',
    storageBucket: 'buooy-5d81f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNcsbBZsFOdHVa3s-9P14cwqR6IbKyj0',
    appId: '1:75312656911:ios:abdaad6835648d4901a97a',
    messagingSenderId: '75312656911',
    projectId: 'buooy-5d81f',
    storageBucket: 'buooy-5d81f.firebasestorage.app',
    iosBundleId: 'com.example.buooyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNcsbBZsFOdHVa3s-9P14cwqR6IbKyj0',
    appId: '1:75312656911:ios:abdaad6835648d4901a97a',
    messagingSenderId: '75312656911',
    projectId: 'buooy-5d81f',
    storageBucket: 'buooy-5d81f.firebasestorage.app',
    iosBundleId: 'com.example.buooyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABe1sO3_Dy_9fQ6Iqan-hUFKyxto7J2IQ',
    appId: '1:75312656911:web:ef6e77a648489d1d01a97a',
    messagingSenderId: '75312656911',
    projectId: 'buooy-5d81f',
    authDomain: 'buooy-5d81f.firebaseapp.com',
    storageBucket: 'buooy-5d81f.firebasestorage.app',
    measurementId: 'G-G4HW4T9JWK',
  );

}